command: ['streamlit', 'run', 'app.py']
env:
  - name: 'DATABRICKS_TOKEN'
    valueFrom: 'DATABRICKS_TOKEN'
  - name: 'DATABRICKS_HOST'
    valueFrom: 'DATABRICKS_HOST'
  - name: 'DATABRICKS_BASE_URL'
    valueFrom: 'DATABRICKS_BASE_URL'
  - name: 'DATABRICKS_MODEL'
    valueFrom: 'DATABRICKS_MODEL'
  - name: 'GENIE_SPACE_ID'
    valueFrom: 'GENIE_SPACE_ID'
  - name: 'GENIE_SPACE_PRODUCT_INV_ID'
    valueFrom: 'GENIE_SPACE_PRODUCT_INV_ID'
  - name: 'MLFLOW_EXPERIMENT_ID'
    valueFrom: 'MLFLOW_EXPERIMENT_ID'
  - name: 'CENSUS_API_KEY'
    valueFrom: 'CENSUS_API_KEY'
  - name: 'PERPLEXITY_API_KEY'
    valueFrom: 'PERPLEXITY_API_KEY'
